version: '2'
services:
  nginx:
    image: nginx:1.13.3
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/.bundle:/etc/nginx/front
      - /etc/letsencrypt:/etc/letsencrypt

  api:
    build: ./api
    restart: always
    environment:
      - MAIL_PORT
      - MAIL_SERVER
      - MAIL_USERNAME
      - MAIL_PASSWORD
