version: '2'
services:
  nginx:
    image: nginx:1.13.3
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.bundle/:/etc/nginx/bundle/
      - /etc/letsencrypt:/etc/letsencrypt/
