baseURL = "https://romancev.com/blog/"
languageCode = "en-us"
title = "Andrey Romancev"
theme = "ananke"

disqusShortname = "romancev"
MetaDataFormat = "yaml"

[sitemap]
  changefreq = "weekly"

[params]
  favicon = ""
  github = "https://github.com/andreyromancev"
  description = "Andrey Romancev personal web site."
  twitter = "#"
  linkedin = "https://www.linkedin.com/in/romancev/"
  featured_image = "/images/background.jpg"
  recent_posts_number = 3
  custom_css = ["/css/main.css"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://romancev.com/"

  [[menu.main]]
    identifier = "blog"
    name = "Articles"
    url = "/"
